<?php
	include ("../modelo/mencuapren.php");
	$ins = new mencuapren();
	ini_set("memory_limit", "64M");
	require_once("../dompdf/dompdf_config.inc.php");
	$pr = isset($_GET["pr"]) ? $_GET["pr"]:NULL;
    $dat = $ins->seluse1($pr);
    $dat1 = $ins->seluse2($pr);
    $dat2 = $ins->seluse3();
        $html = '<html><head>';
        $html .= '</head><body>';
		$html .= '<div align="center">';
		$html .= '<table width="600px"   align="center" border="0" >';
		$html .= '<tr>';
				$html .= '<td  align="center" colspan="4"  ><font face="Arial" size=1> <h3>FORMATO ENCUESTA DE CARACTERIZACION DE APRENDICES MATRICULADOS <br><br> DIRECCION DE FORMACION PROFESIONAL <br><br> GRUPO DE FOMENTO DEL BIENESTAR Y LIDERAZGO DEL APRENDIZ <br> <br>';
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><b>Fecha</b>';
				$html .= ' : ';
				$html .= date("d-m-Y");
				$html .= '</td>';
				$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><b>Centro de formacion</b>';
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left"><font face="Arial" size=1 style="text-transform: capitalize;"><b>Subsede</b>';
				$html .= '</td>';
				$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><b>Regional</b>';
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="center" colspan="4"> <font face="Arial" size=1><h4>DATOS BASICOS DEL APRENDIZ<br><br>';
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="4" > <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>1. Nombre Del Aprendiz</b>';
				$html .= ' : ';
				$html .= $dat[0]["nomapre"];
				$html .= ' ';
				$html .= $dat[0]["apeapre"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>2. Tipo De Documento</b>';
				$html .= ' : ';
				$html .= $dat[0]["nomval"];
				$html .= '</td>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>3. Numero de Documento</b>';
				$html .= ': ';
				$html .= $dat[0]["ndocapre"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>4. Sangre</b>';
				$html .= ': ';
				$html .= $dat[0]["sangre"];
				$html .= '</td>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>5. Genero</b>';
				$html .= ': ';
				$html .= $dat[0]["genero"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>6. Telefono</b>';
				$html .= ': ';
				$html .= $dat[0]["telapre"];
				$html .= '</td>';
				$html .= '<td align="left"colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>7. No.2 Telefono</b>';
				$html .= ': ';
				$html .= $dat[0]["telefono"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>8. libreta Militar </b>';
				$html .= ': ';
				$html .= $dat[0]["nlmiapre"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>9. Estado Civil</b>';
				$html .= ': ';
				$html .= $dat[0]["civil"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>10. Correo Electronico </b>';
				$html .= ': ';;
				$html .= $dat[0]["emaapre"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>11. No.2 Correo Electronico </b>';
				$html .= ': ';;
				$html .= $dat[0]["email"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>12. Municipio Residencia</b>';
				$html .= ': ';
				$html .= $dat[0]["ciudad"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"><font face="Arial" size=1 style="text-transform: capitalize;"><br><b>13. Departamento Recidencia</b>';
				$html .= ': ';
				$html .= $dat[0]["departamento"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>14. Fecha Nacimiento</b>';
				$html .= ': ';
				$html .= $dat[0]["fenaapre"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"><font face="Arial" size=1 style="text-transform: capitalize;"><br><b>15. Programa De Formacion</b>';
				$html .= ': ';
				$html .= $dat[0]["nompro"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"><font face="Arial" size=1 style="text-transform: capitalize;"><br><b>16. Numero Ficha</b> ';
				$html .= ': ';
				$html .= $dat[0]["nfic"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>17. Inicio Programa</b>';
				$html .= ': ';
				$html .= $dat[0]["finific"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>18. Fin Pprograma</b>';
				$html .= ': ';
				$html .= $dat[0]["ffinfic"];
				$html .= '</td>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>19. Jornada </b>';
				$html .= ': ';
				$html .= $dat[0]["jornada"];
				$html .= '</td>';
		$html .= '</tr>';
		$html .= '<tr>';
			$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>22. Direccion Residencia</b>';
			$html .= ': ';
			$html .= $dat[0]["dirapre"];
			$html .= '</td>';
			$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>20. Emergencias Persona</b>';
				$html .= ': ';
				$html .= $dat[0]["llamaapre"];
				$html .= '</td>';
		$html .= '</tr>';
			$html .= '<tr>';
				$html .= '<td align="left" colspan="2"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>21. Emergencias Llamar</b> ';
				$html .= ': ';
				$html .= $dat[0]["teleapre"];
				$html .= '</td>';
		$html .= '</tr>';
	 $a=0;
	 $b=22;
		for ($j=0; $j < count($dat1); $j++){
			 	$a++;
				if($a%2==1){
					$html .= '<tr>';
					$b++;
					$html .= ' <td align="left" > <font face="Arial" size=1 style="text-transform: capitalize;"> <br><b>'.$b;
					$html .= '. ';
					$html .= $dat1[$j]["despre"];
					$html .= '</b><br>';
					$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><br>';
						for ($p=0; $p < count($dat2); $p++){
								if($dat1[$j]["codpre"]==$dat2[$p]["codpre"]){
											$html .= $dat2[$p]["resrap"];
											$html .= '<br>';	
								}
						}
					$html .= '</td>';
					$html .= '</td>';
				}else{
					$b++;
					$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>'.$b;
					$html .= '. ';
					$html .= $dat1[$j]["despre"];
					$html .= '</b><br>';
					$html .= '<td align="left"> <font face="Arial" size=1 style="text-transform: capitalize;"><br>';
						for ($p=0; $p < count($dat2); $p++){
								if($dat1[$j]["codpre"]==$dat2[$p]["codpre"]){
											$html .= $dat2[$p]["resrap"];
											$html .= '<br>';
								}
						}
					$html .= '</td>';
					$html .= '</td>';
					$html .= '</tr>';
				}
		}
		$html .= '</table>';
		$html .= '</div>';
		$html .= '</body>';
		$html .= '</html>';
		$dompdf = new DOMPDF(); 
		$dompdf->load_html($html); 
		$dompdf->render(); 
		$dompdf->stream("Encuesta_".$dat[0]["nombre"].".pdf");
?>