<?php
	include ("../modelo/mencuapren.php");
	$ins = new mencuapren();
	$pr = isset($_GET["pr"]) ? $_GET["pr"]:NULL;
    $dat = $ins->seluse5();
	ob_start();
	 $html = '<table width="650px"   align="center" border="1" >';
	$html .= '<tr>';
				$html .= '<td  align="center" colspan="18" ><font face="Arial" size=1> <h3>APRENDICEZ REGISTRADOS <br> <br>';
				$html .= '</td>';
	$html .= '</tr>';
		$html .= '<tr>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Nombre Del Aprendiz</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Tipo De Documento</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Numero de Documento</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Sangre</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Telefono</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>No.2 Telefono</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Genero</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>libreta Militar </b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Estado Civil</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Direccion Residencia</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Correo Electronico </b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>No.2 Correo Electronico </b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Municipio Residencia</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Departamento Recidencia</b></td></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Programa De Formacion</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Numero Ficha</b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Jornada </b></td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;"><br><b>Fecha En Que Se Registro </b></td>';
		$html .= '</tr>';
		for ($j=0; $j < count($dat); $j++){
		$html .= '<tr>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["nomapre"];
				$html .= ' ';
				$html .= $dat[$j]["apeapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
			$html .= $dat[$j]["nomval"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["ndocapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["sangre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["telapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["telefono"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
			$html .= $dat[$j]["genero"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["nlmiapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["civil"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["dirapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["emaapre"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
			$html .= $dat[$j]["email"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
			$html .= $dat[$j]["ciudad"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["departamento"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["nompro"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["nfic"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["jornada"];
				$html .= '</td>';
				$html .= '<td align="center"> <font face="Arial" size=1 style="text-transform: capitalize;">';
				$html .= $dat[$j]["fechadeinicio"];
				$html .= '</td>';
	$html .= '</tr>';
}

		$html .= '</table>';
		echo $html;
		$reporte=ob_get_clean();
		header("content-type:application/vnd.ms-excel");
		header("content-Disposition:attachment;filename=Reportes De Aprendiz.xls");
		header("Pregma: no-cahe");
		header("Expires:0");
		echo $reporte;
    ?>